version: "3.7"
services:
  node:
    build: ./nodejs
    user: node
    working_dir: /home/node/app
    environment:
      NODE_ENV: production
      WAIT_HOSTS: mongodb:27017
    expose:
      - "3000"
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    container_name: mongodb
    expose:
      - "27017"
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: qrhunt
volumes:
  mongodb_data:
    driver: local